import { font } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body className={cn('dark', font.className)}>
        {children}
      </body>
    </html>
  )
}
